version: '3.4'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy-nginx
    volumes:
      - nginx-proxy/certs:/etc/nginx/certs
      - nginx-proxy/vhost:/etc/nginx/vhost.d
      - nginx-proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443

  proxy-nginx-ssl:
    image: nginxproxy/acme-companion
    container_name: proxy-nginx-ssl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy/acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=eth3rnit3@gmail.com
      - NGINX_PROXY_CONTAINER=proxy-nginx

volumes:
  nginx-proxy:

networks:
  default:
    name: nginx-proxy