version: '3.4'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy-nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443

networks:
  default:
    name: nginx-proxy